# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b69cbcfaef6e94ef86a80cc39b1ceef5"
name = "product-review"
handle = "product-review-87"
application_url = "https://unavailable-nervous-flow-fairfield.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "productinsight-review.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://unavailable-nervous-flow-fairfield.trycloudflare.com/auth/callback",
  "https://unavailable-nervous-flow-fairfield.trycloudflare.com/auth/shopify/callback",
  "https://unavailable-nervous-flow-fairfield.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
